wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1630347938
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.9.6
      5: 0.12.1
      8:
      - 5
batch_size:
  desc: null
  value: 32
classes:
  desc: null
  value: 3
dataset:
  desc: null
  value: private
dropout:
  desc: null
  value: 0.2
embedding_dim:
  desc: null
  value: 200
epochs:
  desc: null
  value: 140
hidden_dim:
  desc: null
  value:
  - 32
  - 32
  - 32
learning_rate:
  desc: null
  value: 0.0001
